
import { RealTimeMessage, ThreadEvent, ThreadEventSchema } from "@/app/schemas/realtime";
import { orpc } from "@/lib/orpc";
import { useQueryClient } from "@tanstack/react-query";
import usePartySocket from "partysocket/react";
import { createContext, ReactNode, useContext, useMemo } from "react";

interface ThreadRealtimeProviderProps{
    threadId: string;
    children: ReactNode;
}

type ThreadRealtimeContextvalue={
    send: (e:ThreadEvent)=>void;
}
type ThreadListOtions=ReturnType<
typeof orpc.message.thread.list.queryOptions>;
type ThreadQueryData=Awaited<ReturnType<ThreadListOtions["queryFn"]>>;

const ThreadRealtimeContext=createContext<ThreadRealtimeContextvalue | null>(null);

export function ThreadRealtimeProvider({children,threadId}:ThreadRealtimeProviderProps){
    const queryClient = useQueryClient();
    const socket = usePartySocket({
        host: 'https://teamflow-chat-realtime.piyushkum2005.workers.dev',
        room: `thread-${threadId}`,
        party: 'chat',
        onMessage(e){
            try{
                const parsed=JSON.parse(e.data);
                const result=ThreadEventSchema.safeParse(parsed);
                if(!result.success){
                    console.log("Invalid thread Event");
                    return;
                }
                const event=result.data;
                if(event.type==="thread:reply:created"){
                    //use the same key generated by orpc
                    const  replyObj = event.payload.reply as RealTimeMessage;
                    const listOptions=orpc.message.thread.list.queryOptions({
                        input: {messageId:threadId},
                    });
                    queryClient.setQueryData<ThreadQueryData>(
                        listOptions.queryKey,
                        (old)=>{
                            if(!old) return old;
                            const reply ={
                                reactions: Array.isArray(replyObj.reactions) ? replyObj.reactions : [],
                                ...replyObj,
                            } as ThreadQueryData['messages'][number];
                            return {
                                ...old,
                                messages: [...old.messages,reply],
                            }
                        },
                    );
                    return;
                }
                if(event.type==="thread:reaction:updated"){
                    const {messageId,reactions,threadId:tid}=event.payload;
                    if(tid===threadId){
                        return;
                    }
                    const listOptions=orpc.message.thread.list.queryOptions({
                        input: {messageId:threadId},
                    });
                    queryClient.setQueryData(
                        listOptions.queryKey,
                        (old)=>{
                            if(!old){
                                return old;
                            }
                            if(messageId===threadId){
                                return {
                                    ...old,
                                    parent: {...old.parent,reactions},
                                };
                            }
                            return {
                                ...old,
                                messages: old.messages.map((m)=>m.id===messageId ? {...m,reactions}: m),
                            };
                        }
                    );
                    return;
                }
            }catch{
                console.log("Something went wrong");
            }
        }
    });
    const value=useMemo(()=>{
        return {
            send: (e:ThreadEvent)=>{
                socket.send(JSON.stringify(e));
            },
        }
    },[socket]);
    return (
        <ThreadRealtimeContext.Provider value={value}>
            {children}
        </ThreadRealtimeContext.Provider>
    );
}

export function useThreadRealtime(){
    const ctx=useContext(ThreadRealtimeContext);
    if(!ctx){
        throw new Error('useThreadRealtime must be used within a ThreadRealtimeProvider');
    }
    return ctx;
}
export function useOptionalThreadRealtime():ThreadRealtimeContextvalue | null{
    return useContext(ThreadRealtimeContext);
}